### ISSUE TITLE
(null): イ形容詞アウオ段  does not have katuyou  (null)  in  JUMAN.katuyou .

### ISSUE THREAD

**Issue by shohei-ta-ds7** [ku-nlp/knp#9]
「京都の夏は暑いねぇ」のようなくだけた日本語を入力すると下記のようなエラーが出てプログラムが終了する．
```
$ echo '京都の夏は暑いねぇ' | jumanpp | knp -tab | knp

(null): イ形容詞アウオ段  does not have katuyou  (null)  in  JUMAN.katuyou .
exit(11)
```
「京都の夏は暑いね」のように修正すると問題なく解析結果が出力される．
JUMAN および KNP のバージョンは下記の通り．
juman 7.01
knp 5.0 (Revision.0209a5ef on 2021-02-06)

**Comment by dkawahara** [comment]
JUMAN 7.01とJuman++が使っている文法・活用情報のバージョンが異なることが原因のように思います。KNPのインストール時に./configureに--with-included-jumanオプションを付加して試していただけますでしょうか。このオプションによって、Juman++ (2.0.0-rc3)と同じバージョンの文法・活用ファイルがインストールされます。

**Comment by shohei-ta-ds7** [comment]
上記のエラーについて，指示していただいた通り対応したところ解決しました．
迅速なご対応ありがとうございました．
